title: Dreaming dreams no mortal ever dared to dream before...
author: Benn-bit
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Wakey Wakey, rise and shine, it's on again off again on again...
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
